name: "Auto Release"
# This command runs periodically and attempts to create and submit
# a new version of the app to the App Store.
on:
  #push:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  create-release:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: swift run fairtool version

      - name: Bump release
        run: |
            swift run fairtool app configure --bump patch | tee /tmp/fairv.json
            TAGNAME=`cat /tmp/fairv.json | jq -re '.[0].version'`
            git add appfair.xcconfig
            git commit -m "Auto-release ${TAGNAME}"
            git tag -s -a "${TAGNAME}" -m "Release ${TAGNAME}"
            git push --follow-tags

