name: "Auto Release"
on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: |
          swift run fairtool version

