name: "Auto Release"

# This command runs periodically and attempts to create and submit
# a new version of the app to the App Store.
on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2
        with:
            token: ${{ env.GITHUB_TOKEN }}

      - name: Run fairtool
        run: swift run fairtool version

      - name: Bump release
        run: |
          swift run fairtool app configure -J --bump patch | tee /tmp/fairv.json

          APPNAME=`cat /tmp/fairv.json | jq -re '.productName'`
          APPID=`cat /tmp/fairv.json | jq -re '.bundleIdentifier'`
          TAGNAME=`cat /tmp/fairv.json | jq -re '.version'`

          git config --global user.name 'fair-ground action'
          git config --global user.email 'fair-ground@users.noreply.github.com'

          # Trigger the release
          git add appfair.xcconfig
          git commit -m "Auto-release ${TAGNAME}"
          git tag -a "${TAGNAME}" -m "Release ${TAGNAME}"
          git push --follow-tags

          cat .git/config

          # Trigger the integration
          gh pr create --repo appfair/App --title "${APPNAME} ${TAGNAME}" --body "Auto-release ${TAGNAME}"

