name: "Release App"
# Release App creates a release of the app and issues a release PR.
#
# See: https://www.appfair.net
on: 
  # Releases can be scheduled (e.g., weekly) if an access token is specified
  #schedule:
  #  - cron: '0 0 0 * *'
  workflow_dispatch:
    inputs:
      bump_major:
        type: boolean
        description: 'Bump Version Major'
        default: false
      bump_minor:
        type: boolean
        description: 'Bump Version Minor'
        default: false
      bump_patch:
        type: boolean
        description: 'Bump Version Patch'
        default: true
      version:
        type: string
        description: 'Specific App Version'
        required: false

jobs:
  call-workflow:
    uses: appfair/fairground/.github/workflows/release.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      bump_major: ${{ github.event.inputs.bump_major == 'true' }}
      bump_minor: ${{ github.event.inputs.bump_minor == 'true' }}
      bump_patch: ${{ github.event.inputs.bump_patch == 'true' }}

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

