name: "Release App"
# Release App creates a release of the app and issues a release PR.
#
# See: https://www.appfair.net
on: 
  # Releases can be scheduled (e.g., weekly) if an access token is specified
  schedule:
    - cron: '46 * * * *'
    #- cron: '0 0,8,16 * * *'
  workflow_dispatch:
    inputs:
      bump_major:
        type: boolean
        description: 'Bump major version'
        default: false
      bump_minor:
        type: boolean
        description: 'Bump minor version'
        default: false
      bump_patch:
        type: boolean
        description: 'Bump patch version'
        default: true
      version:
        type: string
        description: 'Set specific version'
        required: false

jobs:
  call-workflow:
    uses: appfair/fairground/.github/workflows/release.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      bump_major: ${{ github.event.inputs.bump_major == 'true' }}
      bump_minor: ${{ github.event.inputs.bump_minor == 'true' }}
      bump_patch: ${{ github.event.inputs.bump_patch == 'true' }}
    permissions:
      contents: write
      pull-requests: write
    secrets:
      # Requires org settings
      # https://github.com/organizations/Silly-Little-App/settings/actions
      # to enable "Allow GitHub Actions to create and approve pull requests"
      #token: ${{ secrets.GITHUB_TOKEN }}
      token: ${{ secrets.APP_FAIR_BOT_SLA_TOKEN }}

